# Copyright (c) Microsoft. All rights reserved.
trigger: none

pool:
  vmImage: 'windows-latest'
  
variables:
  - name: solution
    value: 'Microsoft.MyWorkspace.Scheduler'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'


name: PR_$(Date:yyMMdd)$(Rev:.r)

stages:
  - stage: NonProd_CheckCodeQuality
    jobs:
      - template: ../templates/codequality-stage.yml
        parameters:
          solution: '$(solution)'
          projectFolder: ['Microsoft.MyWorkspace.Scheduler.Models', 'Microsoft.MyWorkspace.Scheduler.Repository', 'Microsoft.MyWorkspace.Scheduler.Worker' ]
          buildPlatform: '$(buildPlatform)'
          buildConfiguration: '$(buildConfiguration)'