export const FETCH_TEMPLATES_BEGIN = 'FETCH_TEMPLATES_BEGIN';
export const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = 'FETCH_TEMPLATES_FAILURE';

export const FETCH_INITIAL_AUTHOR_TEMPLATES_BEGIN =
  'FETCH_INITIAL_AUTHOR_TEMPLATES_BEGIN';
export const FETCH_INITIAL_AUTHOR_TEMPLATES_SUCCESS =
  'FETCH_INITIAL_AUTHOR_TEMPLATES_SUCCESS';
export const FETCH_INITIAL_AUTHOR_TEMPLATES_ODATA_SUCCESS =
  'FETCH_INITIAL_AUTHOR_TEMPLATES_ODATA_SUCCESS';
export const FETCH_INITIAL_AUTHOR_TEMPLATES_FAILURE =
  'FETCH_INITIAL_AUTHOR_TEMPLATES_FAILURE';

export const FETCH_NEXT_AUTHOR_TEMPLATES_BEGIN =
  'FETCH_NEXT_AUTHOR_TEMPLATES_BEGIN';
export const FETCH_NEXT_AUTHOR_TEMPLATES_SUCCESS =
  'FETCH_NEXT_AUTHOR_TEMPLATES_SUCCESS';
export const FETCH_NEXT_AUTHOR_TEMPLATES_ODATA_SUCCESS =
  'FETCH_NEXT_AUTHOR_TEMPLATES_ODATA_SUCCESS';
export const FETCH_NEXT_AUTHOR_TEMPLATES_FAILURE =
  'FETCH_NEXT_AUTHOR_TEMPLATES_FAILURE';

export const REFRESH_AUTHOR_TEMPLATES_BEGIN = 'REFRESH_AUTHOR_TEMPLATES_BEGIN';
export const REFRESH_AUTHOR_TEMPLATES_SUCCESS =
  'REFRESH_AUTHOR_TEMPLATES_SUCCESS';
export const REFRESH_AUTHOR_TEMPLATES_ODATA_SUCCESS =
  'REFRESH_AUTHOR_TEMPLATES_ODATA_SUCCESS';
export const REFRESH_AUTHOR_TEMPLATES_FAILURE =
  'REFRESH_AUTHOR_TEMPLATES_FAILURE';

export const UPDATE_TEMPLATE_BEGIN = 'UPDATE_TEMPLATE_BEGIN';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAILURE = 'UPDATE_TEMPLATE_FAILURE';

export const DELETE_TEMPLATE_BEGIN = 'DELETE_TEMPLATE_BEGIN';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAILURE = 'DELETE_TEMPLATE_FAILURE';

export const CREATE_TEMPLATE_BEGIN = 'CREATE_TEMPLATE_BEGIN';
export const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAILURE = 'CREATE_TEMPLATE_FAILURE';

export const SET_TEMPLATE_REQUESTS = 'SET_TEMPLATE_REQUESTS';
export const SET_TEMPLATE_REQUESTS_FILTER_PROPERTIES =
  'SET_TEMPLATE_REQUESTS_FILTER_PROPERTIES';
export const SET_TEMPLATE_REQUESTS_SORT_PROPERTY =
  'SET_TEMPLATE_REQUESTS_SORT_PROPERTY';
