export const FETCH_ADMIN_DIAGNOSTIC_BEGIN = 'FETCH_ADMIN_DIAGNOSTIC_BEGIN';
export const FETCH_ADMIN_DIAGNOSTIC_SUCCESS = 'FETCH_ADMIN_DIAGNOSTIC_SUCCESS';
export const FETCH_ADMIN_DIAGNOSTIC_FAILURE = 'FETCH_ADMIN_DIAGNOSTIC_FAILURE';

export const FETCH_ADMIN_DIAGNOSTIC_CATEGORY_BEGIN =
  'FETCH_ADMIN_DIAGNOSTIC_CATEGORY_BEGIN';
export const FETCH_ADMIN_DIAGNOSTIC_CATEGORY_SUCCESS =
  'FETCH_ADMIN_DIAGNOSTIC_CATEGORY_SUCCESS';
export const FETCH_ADMIN_DIAGNOSTIC_CATEGORY_FAILURE =
  'FETCH_ADMIN_DIAGNOSTIC_CATEGORY_FAILURE';

export const RUN_SELECTED_ADMIN_DIAGNOSTIC_BEGIN =
  'RUN_SELECTED_ADMIN_DIAGNOSTIC_BEGIN';
export const RUN_SELECTED_ADMIN_DIAGNOSTIC_SUCCESS =
  'RUN_SELECTED_ADMIN_DIAGNOSTIC_SUCCESS';
export const RUN_SELECTED_ADMIN_DIAGNOSTIC_FAILURE =
  'RUN_SELECTED_ADMIN_DIAGNOSTIC_FAILURE';

export const FETCH_CURRENT_DIAGNOSTIC_BEGIN = 'FETCH_CURRENT_DIAGNOSTIC_BEGIN';
export const FETCH_CURRENT_DIAGNOSTIC_SUCCESS =
  'FETCH_CURRENT_DIAGNOSTIC_SUCCESS';
export const FETCH_CURRENT_DIAGNOSTIC_FAILURE =
  'FETCH_CURRENT_DIAGNOSTIC_FAILURE';

export const RUN_SELECTED_SOLUTION_BEGIN = 'RUN_SELECTED_SOLUTION_BEGIN';
export const RUN_SELECTED_SOLUTION_SUCCESS = 'RUN_SELECTED_SOLUTION_SUCCESS';
export const RUN_SELECTED_SOLUTION_FAILURE = 'RUN_SELECTED_SOLUTION_FAILURE';
