export const FETCH_ADMIN_FIREWALLS_BEGIN = 'FETCH_ADMIN_FIREWALLS_BEGIN';
export const FETCH_ADMIN_FIREWALLS_SUCCESS = 'FETCH_ADMIN_FIREWALLS_SUCCESS';
export const FETCH_ADMIN_FIREWALLS_FAILURE = 'FETCH_ADMIN_FIREWALLS_FAILURE';

export const SET_SELECTED_ADMIN_FIREWALL = 'SET_SELECTED_ADMIN_FIREWALL_ID';
export const SET_SELECTED_ADMIN_FIREWALL_HUB =
  'SET_SELECTED_ADMIN_FIREWALL_HUB';

export const UPDATE_SELECTED_ADMIN_FIREWALL = 'UPDATE_SELECTED_ADMIN_FIREWALL';
export const UPDATE_SELECTED_ADMIN_FIREWALL_HUB =
  'UPDATE_SELECTED_ADMIN_FIREWALL_HUB';

export const RESET_SELECTED_ADMIN_FIREWALL = 'RESET_SELECTED_ADMIN_FIREWALL';
export const RESET_SELECTED_ADMIN_FIREWALL_HUB =
  'RESET_SELECTED_ADMIN_FIREWALL_HUB';

export const UPDATE_FIREWALL_SETTINGS_BEGIN = 'UPDATE_FIREWALL_SETTINGS_BEGIN';
export const UPDATE_FIREWALL_SETTINGS_SUCCESS =
  'UPDATE_FIREWALL_SETTINGS_SUCCESS';
export const UPDATE_FIREWALL_SETTINGS_FAILURE =
  'UPDATE_FIREWALL_SETTINGS_FAILURE';

export const UPDATE_HUB_NETWORK_BEGIN = 'UPDATE_HUB_NETWORK_BEGIN';
export const UPDATE_HUB_NETWORK_SUCCESS = 'UPDATE_HUB_NETWORK_SUCCESS';
export const UPDATE_HUB_NETWORK_FAILURE = 'UPDATE_HUB_NETWORK_FAILURE';

export const CREATE_FIREWALL_SETTINGS_BEGIN = 'CREATE_FIREWALL_SETTINGS_BEGIN';
export const CREATE_FIREWALL_SETTINGS_SUCCESS =
  'CREATE_FIREWALL_SETTINGS_SUCCESS';
export const CREATE_FIREWALL_SETTINGS_FAILURE =
  'CREATE_FIREWALL_SETTINGS_FAILURE';

export const CREATE_HUB_NETWORK_BEGIN = 'CREATE_HUB_NETWORK_BEGIN';
export const CREATE_HUB_NETWORK_SUCCESS = 'CREATE_HUB_NETWORK_SUCCESS';
export const CREATE_HUB_NETWORK_FAILURE = 'CREATE_HUB_NETWORK_FAILURE';

export const SET_NEW_FIREWALL_SETTINGS = 'SET_NEW_FIREWALL_SETTINGS';
export const SET_NEW_HUB_NETWORK = 'SET_NEW_HUB_NETWORK';

export const UPDATE_NEW_FIREWALL_SETTINGS = 'UPDATE_NEW_FIREWALL_SETTINGS';
export const UPDATE_NEW_HUB_NETWORK = 'UPDATE_NEW_HUB_NETWORK';

export const FETCH_ADMIN_CONFIG_PROFILES_BEGIN =
  'FETCH_ADMIN_CONFIG_PROFILES_BEGIN';
export const FETCH_ADMIN_CONFIG_PROFILES_SUCCESS =
  'FETCH_ADMIN_CONFIG_PROFILES_SUCCESS';
export const FETCH_ADMIN_CONFIG_PROFILES_FAILURE =
  'FETCH_ADMIN_CONFIG_PROFILES_FAILURE';

export const UPDATE_NEW_CONFIG_PROFILE = 'UPDATE_NEW_CONFIG_PROFILE';
export const SET_SELECTED_CONFIG_PROFILE = 'SET_SELECTED_CONFIG_PROFILE';
export const UPDATE_SELECTED_CONFIG_PROFILE = 'UPDATE_SELECTED_CONFIG_PROFILE';
export const RESET_SELECTED_CONFIG_PROFILE = 'RESET_SELECTED_CONFIG_PROFILE';
export const CREATE_CONFIG_PROFILE_BEGIN = 'CREATE_CONFIG_PROFILE_BEGIN';
export const CREATE_CONFIG_PROFILE_SUCCESS = 'CREATE_CONFIG_PROFILE_SUCCESS';
export const CREATE_CONFIG_PROFILE_FAILURE = 'CREATE_CONFIG_PROFILE_FAILURE';
export const RESET_NEW_CONFIG_PROFILE = 'RESET_NEW_CONFIG_PROFILE';
export const SAVE_SELECTED_CONFIG_PROFILE_BEGIN =
  'SAVE_SELECTED_CONFIG_PROFILE_BEGIN';
export const SAVE_SELECTED_CONFIG_PROFILE_SUCCESS =
  'SAVE_SELECTED_CONFIG_PROFILE_SUCCESS';
export const SAVE_SELECTED_CONFIG_PROFILE_FAILURE =
  'SAVE_SELECTED_CONFIG_PROFILE_FAILURE';
export const DELETE_SELECTED_CONFIG_PROFILE_BEGIN =
  'DELETE_SELECTED_CONFIG_PROFILE_BEGIN';
export const DELETE_SELECTED_CONFIG_PROFILE_SUCCESS =
  'DELETE_SELECTED_CONFIG_PROFILE_SUCCESS';
export const DELETE_SELECTED_CONFIG_PROFILE_FAILURE =
  'DELETE_SELECTED_CONFIG_PROFILE_FAILURE';

export const SET_SELECTED_FIREWALLS = 'SET_SELECTED_FIREWALLS';
export const CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_BEGIN =
  'CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_BEGIN';
export const CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_SUCCESS =
  'CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_SUCCESS';
export const CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_FAILURE =
  'CREATE_HUB_NETWORK_DNS_RECORD_CREATION_JOB_FAILURE';

// Firewall deployment.
export const FETCH_FIREWALL_DEPLOYMENT_REGION_BEGIN =
  'FETCH_FIREWALL_DEPLOYMENT_REGION_BEGIN';
export const FETCH_FIREWALL_DEPLOYMENT_REGION_FAILURE =
  'FETCH_FIREWALL_DEPLOYMENT_REGION_FAILURE';
export const FETCH_FIREWALL_DEPLOYMENT_REGION_SUCCESS =
  'FETCH_FIREWALL_DEPLOYMENT_REGION_SUCCESS';
export const DEPLOY_NEW_FIREWALL_BEGIN = 'DEPLOY_NEW_FIREWALL_BEGIN';
export const DEPLOY_NEW_FIREWALL_FAILURE = 'DEPLOY_NEW_FIREWALL_FAILURE';
export const DEPLOY_NEW_FIREWALL_SUCCESS = 'DEPLOY_NEW_FIREWALL_SUCCESS';
export const UPDATE_NEW_FIREWALL_DEPLOYMENT = 'UPDATE_NEW_FIREWALL_DEPLOYMENT';
export const SET_NEW_FIREWALL_DEPLOYMENT = 'SET_NEW_FIREWALL_DEPLOYMENT';

// Firewall tenant.
export const FETCH_FIREWALL_TENANTS_BEGIN = 'FETCH_FIREWALL_TENANT_BEGIN';
export const FETCH_FIREWALL_TENANTS_FAILURE = 'FETCH_FIREWALL_TENANT_FAILURE';
export const FETCH_FIREWALL_TENANTS_SUCCESS = 'FETCH_FIREWALL_TENANT_SUCCESS';

// Firewall software versions
export const FETCH_FIREWALL_SOFTWARE_VERSIONS_BEGIN =
  'FETCH_FIREWALL_SOFTWARE_VERSIONS_BEGIN';
export const FETCH_FIREWALL_SOFTWARE_VERSIONS_FAILURE =
  'FETCH_FIREWALL_SOFTWARE_VERSIONS_FAILURE';
export const FETCH_FIREWALL_SOFTWARE_VERSIONS_SUCCESS =
  'FETCH_FIREWALL_SOFTWARE_VERSIONS_SUCCESS';

// Firewall software update.
export const FIREWALL_SOFTWARE_UPDATE_BEGIN = 'FIREWALL_SOFTWARE_UPDATE_BEGIN';
export const FIREWALL_SOFTWARE_UPDATE_FAILURE =
  'FIREWALL_SOFTWARE_UPDATE_FAILURE';
export const FIREWALL_SOFTWARE_UPDATE_SUCCESS =
  'FIREWALL_SOFTWARE_UPDATE_SUCCESS';
