export const FETCH_USER_ROLE_ASSIGNMENT_BEGIN =
  'FETCH_USER_ROLE_ASSIGNMENT_BEGIN';
export const FETCH_USER_ROLE_ASSIGNMENT_SUCCESS =
  'FETCH_USER_ROLE_ASSIGNMENT_SUCCESS';
export const FETCH_USER_ROLE_ASSIGNMENT_FAILURE =
  'FETCH_USER_ROLE_ASSIGNMENT_FAILURE';
export const FETCH_ADMIN_USER_ROLE_ASSIGNMENT_BEGIN =
  'FETCH_ADMIN_USER_ROLE_ASSIGNMENT_BEGIN';
export const FETCH_ADMIN_USER_ROLE_ASSIGNMENT_SUCCESS =
  'FETCH_ADMIN_USER_ROLE_ASSIGNMENT_SUCCESS';
export const FETCH_ADMIN_USER_ROLE_ASSIGNMENT_FAILURE =
  'FETCH_ADMIN_USER_ROLE_ASSIGNMENT_FAILURE';
export const FETCH_ADMIN_SEGMENTS_BEGIN = 'FETCH_ADMIN_SEGMENTS_BEGIN';
export const FETCH_ADMIN_SEGMENTS_SUCCESS = 'FETCH_ADMIN_SEGMENTS_SUCCESS';
export const FETCH_ADMIN_SEGMENTS_FAILURE = 'FETCH_ADMIN_SEGMENTS_FAILURE';
export const FETCH_SEGMENT_MEMBERS_BEGIN = 'FETCH_SEGMENT_MEMBERS_BEGIN';
export const FETCH_SEGMENT_MEMBERS_SUCCESS = 'FETCH_SEGMENT_MEMBERS_SUCCESS';
export const FETCH_SEGMENT_MEMBERS_FAILURE = 'FETCH_SEGMENT_MEMBERS_FAILURE';
export const APPEND_SEGMENT_MEMBERS_BEGIN = 'APPEND_SEGMENT_MEMBERS_BEGIN';
export const APPEND_SEGMENT_MEMBERS_SUCCESS = 'APPEND_SEGMENT_MEMBERS_SUCCESS';
export const APPEND_SEGMENT_MEMBERS_FAILURE = 'APPEND_SEGMENT_MEMBERS_FAILURE';
export const CLEAR_ADMIN_USER_ROLE_SEARCH = 'CLEAR_ADMIN_USER_ROLE_SEARCH';
export const SET_SELECTED_ADMIN_SEGMENT = 'SET_TENANT_SEGMENT_ADMIN_SEGMENT';
export const SET_TENANT_SEGMENT_USER_EXISTS_QUERY =
  'SET_TENANT_SEGMENT_USER_EXISTS_QUERY';
export const SET_TENANT_SEGMENT_ADMIN_EMAIL_QUERY =
  'SET_TENANT_SEGMENT_ADMIN_EMAIL_QUERY';
export const ADD_SEGMENT_MEMBER_BEGIN = 'ADD_SEGMENT_MEMBER_BEGIN';
export const ADD_SEGMENT_MEMBER_SUCCESS = 'ADD_SEGMENT_MEMBER_SUCCESS';
export const ADD_SEGMENT_MEMBER_FAILURE = 'ADD_SEGMENT_MEMBER_FAILURE';
export const FETCH_WORKSPACE_INSIGHTS_BEGIN = 'FETCH_WORKSPACE_INSIGHTS_BEGIN';
export const FETCH_WORKSPACE_INSIGHTS_SUCCESS =
  'FETCH_WORKSPACE_INSIGHTS_SUCCESS';
export const FETCH_WORKSPACE_INSIGHTS_ODATA_SUCCESS =
  'FETCH_WORKSPACE_INSIGHTS_ODATA_SUCCESS';
export const FETCH_WORKSPACE_INSIGHTS_FAILURE =
  'FETCH_WORKSPACE_INSIGHTS_FAILURE';
export const FETCH_USER_WORKSPACE_INSIGHTS_BEGIN =
  'FETCH_USER_WORKSPACE_INSIGHTS_BEGIN';
export const FETCH_USER_WORKSPACE_INSIGHTS_SUCCESS =
  'FETCH_USER_WORKSPACE_INSIGHTS_SUCCESS';
export const FETCH_USER_WORKSPACE_INSIGHTS_ODATA_SUCCESS =
  'FETCH_USER_WORKSPACE_INSIGHTS_ODATA_SUCCESS';
export const FETCH_USER_WORKSPACE_INSIGHTS_FAILURE =
  'FETCH_USER_WORKSPACE_INSIGHTS_FAILURE';
export const APPEND_WORKSPACE_INSIGHTS_BEGIN =
  'APPEND_WORKSPACE_INSIGHTS_BEGIN';
export const APPEND_WORKSPACE_INSIGHTS_SUCCESS =
  'APPEND_WORKSPACE_INSIGHTS_SUCCESS';
export const APPEND_WORKSPACE_INSIGHTS_ODATA_SUCCESS =
  'APPEND_WORKSPACE_INSIGHTS_ODATA_SUCCESS';
export const APPEND_WORKSPACE_INSIGHTS_FAILURE =
  'APPEND_WORKSPACE_INSIGHTS_FAILURE';
export const SET_WORKSPACE_INSIGHTS_SORT_PROPERTY =
  'SET_WORKSPACE_INSIGHTS_SORT_PROPERTY';
export const SET_WORKSPACE_INSIGHTS_FILTER_PROPERTIES =
  'SET_WORKSPACE_INSIGHTS_FILTER_PROPERTIES';
export const FETCH_WORKSPACE_INSIGHTS_SUMMARY_BEGIN =
  'FETCH_WORKSPACE_INSIGHTS_SUMMARY_BEGIN';
export const FETCH_WORKSPACE_INSIGHTS_SUMMARY_FAILURE =
  'FETCH_WORKSPACE_INSIGHTS_SUMMARY_FAILURE';
export const FETCH_WORKSPACE_INSIGHTS_SUMMARY_SUCCESS =
  'FETCH_WORKSPACE_INSIGHTS_SUMMARY_SUCCESS ';
export const FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_BEGIN =
  'FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_BEGIN';
export const FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_FAILURE =
  'FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_FAILURE';
export const FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_SUCCESS =
  'FETCH_STALE_WORKSPACE_AUTODELETE_TOTAL_SUCCESS';
export const SET_SELECTED_USERS = 'SET_SELECTED_USERS';
export const SET_SELECTED_WORKSPACE_INSIGHTS =
  'SET_SELECTED_WORKSPACE_INSIGHTS';
export const BULK_DELETE_AZURE_WORKSPACES_BEGIN =
  'BULK_DELETE_AZURE_WORKSPACES_BEGIN';
export const BULK_DELETE_AZURE_WORKSPACES_SUCCESS =
  'BULK_DELETE_AZURE_WORKSPACES_SUCCESS';
export const BULK_DELETE_AZURE_WORKSPACES_FAILURE =
  'BULK_DELETE_AZURE_WORKSPACES_FAILURE';
export const FETCH_SEGMENT_UPDATE_PERCENTAGE_BEGIN =
  'FETCH_SEGMENT_UPDATE_PERCENTAGE_BEGIN';
export const FETCH_SEGMENT_UPDATE_PERCENTAGE_SUCCESS =
  'FETCH_SEGMENT_UPDATE_PERCENTAGE_SUCCESS';
export const FETCH_SEGMENT_UPDATE_PERCENTAGE_FAILURE =
  'FETCH_SEGMENT_UPDATE_PERCENTAGE_FAILURE';
export const PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_BEGIN =
  'PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_BEGIN';
export const PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_SUCCESS =
  'PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_SUCCESS';
export const PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_FAILURE =
  'PATCH_SEGMENT_RESTRICTED_DNS_ADDRESSES_FAILURE';
export const UPDATE_RESTRICTED_ENDPOINTS = 'UPDATE_RESTRICTED_ENDPOINTS';
export const UPDATE_DIRTY_RESTRICTED_ENDPOINTS =
  'UPDATE_DIRTY_RESTRICTED_ENDPOINTS';
export const DELETE_USERS_BEGIN = 'DELETE_USERS_BEGIN';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE';
export const MOVE_SEGMENT_MEMBER_BEGIN = 'MOVE_SEGMENT_MEMBER_BEGIN';
export const MOVE_SEGMENT_MEMBER_SUCCESS = 'MOVE_SEGMENT_MEMBER_SUCCESS';
export const MOVE_SEGMENT_MEMBER_FAILURE = 'MOVE_SEGMENT_MEMBER_FAILURE';
export const FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_BEGIN =
  'FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_BEGIN';
export const FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_SUCCESS =
  'FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_SUCCESS';
export const FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_FAILURE =
  'FETCH_INITIAL_USER_MANAGEMENT_REQUESTS_FAILURE';
export const APPEND_USER_MANAGEMENT_REQUESTS_BEGIN =
  'APPEND_USER_MANAGEMENT_REQUESTS_BEGIN';
export const APPEND_USER_MANAGEMENT_REQUESTS_SUCCESS =
  'APPEND_USER_MANAGEMENT_REQUESTS_SUCCESS';
export const APPEND_USER_MANAGEMENT_REQUESTS_FAILURE =
  'APPEND_USER_MANAGEMENT_REQUESTS_FAILURE';
export const FETCH_USER_MANAGEMENT_REQUEST_UPDATES_BEGIN =
  'FETCH_USER_MANAGEMENT_REQUEST_UPDATES_BEGIN';
export const FETCH_USER_MANAGEMENT_REQUEST_UPDATES_SUCCESS =
  'FETCH_USER_MANAGEMENT_REQUEST_UPDATES_SUCCESS';
export const FETCH_USER_MANAGEMENT_REQUEST_UPDATES_FAILURE =
  'FETCH_USER_MANAGEMENT_REQUEST_UPDATES_FAILURE';
export const SET_SELECTED_USER_MANAGEMENT_REQUESTS =
  'SET_SELECTED_USER_MANAGEMENT_REQUESTS';
export const UPDATE_USER_MANAGEMENT_REQUESTS_BEGIN =
  'UPDATE_USER_MANAGEMENT_REQUESTS_BEGIN';
export const UPDATE_USER_MANAGEMENT_REQUESTS_SUCCESS =
  'UPDATE_USER_MANAGEMENT_REQUESTS_SUCCESS';
export const UPDATE_USER_MANAGEMENT_REQUESTS_FAILURE =
  'UPDATE_USER_MANAGEMENT_REQUESTS_FAILURE';
export const UPDATE_SEGMENT_CONSTRAINT_BEGIN =
  'UPDATE_SEGMENT_CONSTRAINT_BEGIN';
export const UPDATE_SEGMENT_CONSTRAINT_SUCCESS =
  'UPDATE_SEGMENT_CONSTRAINT_SUCCESS';
export const UPDATE_SEGMENT_CONSTRAINT_FAILURE =
  'UPDATE_SEGMENT_CONSTRAINT_FAILURE';
export const UPDATE_EDITABLE_SEGMENT_CONSTRAINT =
  'UPDATE_EDITABLE_SEGMENT_CONSTRAINT';
export const CANCEL_EDITABLE_SEGMENT_CONSTRAINT_CHANGES =
  'CANCEL_EDITABLE_SEGMENT_CONSTRAINT_CHANGES';
export const FETCH_DAILY_SEGMENT_COSTS_BEGIN =
  'FETCH_DAILY_SEGMENT_COSTS_BEGIN';
export const FETCH_DAILY_SEGMENT_COSTS_SUCCESS =
  'FETCH_DAILY_SEGMENT_COSTS_SUCCESS';
export const FETCH_DAILY_SEGMENT_COSTS_FAILURE =
  'FETCH_DAILY_SEGMENT_COSTS_FAILURE';
export const FETCH_MONTHLY_SEGMENT_COSTS_BEGIN =
  'FETCH_MONTHLY_SEGMENT_COSTS_BEGIN';
export const FETCH_MONTHLY_SEGMENT_COSTS_SUCCESS =
  'FETCH_MONTHLY_SEGMENT_COSTS_SUCCESS';
export const FETCH_MONTHLY_SEGMENT_COSTS_FAILURE =
  'FETCH_MONTHLY_SEGMENT_COSTS_FAILURE';
export const SET_COST_GRANULARITY = 'SET_COST_GRANULARITY';
export const SET_COST_DATE_RANGE = 'SET_COST_DATE_RANGE';
export const FETCH_WORKSPACE_COSTS_BEGIN = 'FETCH_WORKSPACE_COSTS_BEGIN';
export const FETCH_WORKSPACE_COSTS_SUCCESS = 'FETCH_WORKSPACE_COSTS_SUCCESS';
export const FETCH_WORKSPACE_COSTS_FAILURE = 'FETCH_WORKSPACE_COSTS_FAILURE';
export const APPEND_WORKSPACE_COSTS_BEGIN = 'APPEND_WORKSPACE_COSTS_BEGIN';
export const APPEND_WORKSPACE_COSTS_SUCCESS = 'APPEND_WORKSPACE_COSTS_SUCCESS';
export const APPEND_WORKSPACE_COSTS_FAILURE = 'APPEND_WORKSPACE_COSTS_FAILURE';
export const FETCH_WORKSPACE_COST_SUMMARY_BEGIN =
  'FETCH_WORKSPACE_COST_SUMMARY_BEGIN';
export const FETCH_WORKSPACE_COST_SUMMARY_SUCCESS =
  'FETCH_WORKSPACE_COST_SUMMARY_SUCCESS';
export const FETCH_WORKSPACE_COST_SUMMARY_FAILURE =
  'FETCH_WORKSPACE_COST_SUMMARY_FAILURE';
export const FETCH_USER_COSTS_BEGIN = 'FETCH_USER_COSTS_BEGIN';
export const FETCH_USER_COSTS_SUCCESS = 'FETCH_USER_COSTS_SUCCESS';
export const FETCH_USER_COSTS_FAILURE = 'FETCH_USER_COSTS_FAILURE';
export const APPEND_USER_COSTS_BEGIN = 'APPEND_USER_COSTS_BEGIN';
export const APPEND_USER_COSTS_SUCCESS = 'APPEND_USER_COSTS_SUCCESS';
export const APPEND_USER_COSTS_FAILURE = 'APPEND_USER_COSTS_FAILURE';
export const FETCH_USER_COST_SUMMARY_BEGIN = 'FETCH_USER_COST_SUMMARY_BEGIN';
export const FETCH_USER_COST_SUMMARY_SUCCESS =
  'FETCH_USER_COST_SUMMARY_SUCCESS';
export const FETCH_USER_COST_SUMMARY_FAILURE =
  'FETCH_USER_COST_SUMMARY_FAILURE';
export const SET_COST_ANALYSIS_EMAIL_QUERY = 'SET_COST_ANALYSIS_EMAIL_QUERY';
export const SET_WORKSPACE_COST_SORT_PROPERTY =
  'SET_WORKSPACE_COST_SORT_PROPERTY';
export const SET_USER_COST_SORT_PROPERTY = 'SET_USER_COST_SORT_PROPERTY';
export const FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_BEGIN =
  'FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_BEGIN';
export const FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_SUCCESS =
  'FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_SUCCESS';
export const FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_FAILURE =
  'FETCH_ALL_PENDING_USER_MANAGEMENT_REQUEST_COUNT_FAILURE';
export const FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_BEGIN =
  'FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_BEGIN';
export const FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_SUCCESS =
  'FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_SUCCESS';
export const FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_FAILURE =
  'FETCH_SEGMENT_PENDING_USER_MANAGEMENT_REQUEST_COUNT_FAILURE';
