export const FETCH_AZURE_WORKSPACES_BEGIN = 'FETCH_AZURE_WORKSPACES_BEGIN';
export const FETCH_AZURE_WORKSPACES_SUCCESS = 'FETCH_AZURE_WORKSPACES_SUCCESS';
export const FETCH_AZURE_WORKSPACES_FAILURE = 'FETCH_AZURE_WORKSPACES_FAILURE';

export const SEARCH_AZURE_WORKSPACE_BEGIN = 'SEARCH_AZURE_WORKSPACE_BEGIN';
export const SEARCH_AZURE_WORKSPACE_SUCCESS = 'SEARCH_AZURE_WORKSPACE_SUCCESS';
export const SEARCH_AZURE_WORKSPACE_FAILURE = 'SEARCH_AZURE_WORKSPACE_FAILURE';

export const CLEAR_AZURE_WORKSPACE_SEARCH = 'CLEAR_AZURE_WORKSPACE_SEARCH';
export const SET_SELECTED_ADMIN_WORKSPACE = 'SET_SELECTED_ADMIN_WORKSPACE';

export const CREATE_AZURE_WORKSPACE_BEGIN = 'CREATE_AZURE_WORKSPACE_BEGIN';
export const CREATE_AZURE_WORKSPACE_SUCCESS = 'CREATE_AZURE_WORKSPACE_SUCCESS';
export const CREATE_AZURE_WORKSPACE_FAILURE = 'CREATE_AZURE_WORKSPACE_FAILURE';

export const UPDATE_AZURE_WORKSPACE_BEGIN = 'UPDATE_AZURE_WORKSPACE_BEGIN';
export const UPDATE_AZURE_WORKSPACE_SUCCESS = 'UPDATE_AZURE_WORKSPACE_SUCCESS';
export const UPDATE_AZURE_WORKSPACE_FAILURE = 'UPDATE_AZURE_WORKSPACE_FAILURE';

export const DELETE_AZURE_WORKSPACE_BEGIN = 'DELETE_AZURE_WORKSPACE_BEGIN';
export const DELETE_AZURE_WORKSPACE_SUCCESS = 'DELETE_AZURE_WORKSPACE_SUCCESS';
export const DELETE_AZURE_WORKSPACE_FAILURE = 'DELETE_AZURE_WORKSPACE_FAILURE';

export const START_STOP_WORKSPACE_BEGIN = 'START_STOP_WORKSPACE_BEGIN';
export const START_STOP_WORKSPACE_SUCCESS = 'START_STOP_WORKSPACE_SUCCESS';
export const START_STOP_WORKSPACE_FAILURE = 'START_STOP_WORKSPACE_FAILURE';

export const START_STOP_MACHINE_BEGIN = 'START_STOP_MACHINE_BEGIN';
export const START_STOP_MACHINE_SUCCESS = 'START_STOP_MACHINE_SUCCESS';
export const START_STOP_MACHINE_FAILURE = 'START_STOP_MACHINE_FAILURE';

export const SAVE_PUBLIC_ADDRESS_CHANGES_BEGIN =
  'SAVE_PUBLIC_ADDRESS_CHANGES_BEGIN';
export const SAVE_PUBLIC_ADDRESS_CHANGES_SUCCESS =
  'SAVE_PUBLIC_ADDRESS_CHANGES_SUCCESS';
export const SAVE_PUBLIC_ADDRESS_CHANGES_FAILURE =
  'SAVE_PUBLIC_ADDRESS_CHANGES_FAILURE';

export const FETCH_PROVISIONING_API_VERSION_BEGIN =
  'FETCH_PROVISIONING_API_VERSION_BEGIN';
export const FETCH_PROVISIONING_API_VERSION_SUCCESS =
  'FETCH_PROVISIONING_API_VERSION_SUCCESS';
export const FETCH_PROVISIONING_API_VERSION_FAILURE =
  'FETCH_PROVISIONING_API_VERSION_FAILURE';

export const CREATE_DNS_ZONE_BEGIN = 'CREATE_DNS_ZONE_BEGIN';
export const CREATE_DNS_ZONE_SUCCESS = 'CREATE_DNS_ZONE_SUCCESS';
export const CREATE_DNS_ZONE_FAILURE = 'CREATE_DNS_ZONE_FAILURE';

export const UPDATE_DNS_ZONE_BEGIN = 'UPDATE_DNS_ZONE_BEGIN';
export const UPDATE_DNS_ZONE_SUCCESS = 'UPDATE_DNS_ZONE_SUCCESS';
export const UPDATE_DNS_ZONE_FAILURE = 'UPDATE_DNS_ZONE_FAILURE';

export const FETCH_ADMIN_AZURE_WORKSPACE_BEGIN =
  'FETCH_ADMIN_AZURE_WORKSPACE_BEGIN';
export const FETCH_ADMIN_AZURE_WORKSPACE_SUCCESS =
  'FETCH_ADMIN_AZURE_WORKSPACE_SUCCESS';
export const FETCH_ADMIN_AZURE_WORKSPACE_FAILURE =
  'FETCH_ADMIN_AZURE_WORKSPACE_FAILURE';

export const FETCH_ADMIN_WORKSPACE_TASKS_BEGIN =
  'FETCH_ADMIN_WORKSPACE_TASKS_BEGIN';
export const FETCH_ADMIN_WORKSPACE_TASKS_SUCCESS =
  'FETCH_ADMIN_WORKSPACE_TASKS_SUCCESS';
export const FETCH_ADMIN_WORKSPACE_TASKS_FAILURE =
  'FETCH_ADMIN_WORKSPACE_TASKS_FAILURE';

export const ADMIN_RETRY_TASK_BEGIN = 'ADMIN_RETRY_TASK_BEGIN';
export const ADMIN_RETRY_TASK_SUCCESS = 'ADMIN_RETRY_TASK_SUCCESS';
export const ADMIN_RETRY_TASK_FAILURE = 'ADMIN_RETRY_TASK_FAILURE';

export const EXTEND_AZURE_WORKSPACE_RUNTIME_BEGIN =
  'EXTEND_AZURE_WORKSPACE_RUNTIME_BEGIN';
export const EXTEND_AZURE_WORKSPACE_RUNTIME_SUCCESS =
  'EXTEND_AZURE_WORKSPACE_RUNTIME_SUCCESS';
export const EXTEND_AZURE_WORKSPACE_RUNTIME_FAILURE =
  'EXTEND_AZURE_WORKSPACE_RUNTIME_FAILURE';

export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const RESET_NIC_BEGIN = 'RESET_NIC_BEGIN';
export const RESET_NIC_SUCCESS = 'RESET_NIC_SUCCESS';
export const RESET_NIC_FAILURE = 'RESET_NIC_FAILURE';

export const ENABLE_PRIVATE_MODE_BEGIN = 'ENABLE_PRIVATE_MODE_BEGIN';
export const ENABLE_PRIVATE_MODE_SUCCESS = 'ENABLE_PRIVATE_MODE_SUCCESS';
export const ENABLE_PRIVATE_MODE_FAILURE = 'ENABLE_PRIVATE_MODE_FAILURE';

export const FETCH_PATCHING_SUMMARY_BEGIN = 'FETCH_PATCHING_SUMMARY_BEGIN';
export const FETCH_PATCHING_SUMMARY_SUCCESS = 'FETCH_PATCHING_SUMMARY_SUCCESS';
export const FETCH_PATCHING_SUMMARY_FAILURE = 'FETCH_PATCHING_SUMMARY_FAILURE';

export const FETCH_PATCHING_DETAILS_BEGIN = 'FETCH_PATCHING_DETAILS_BEGIN';
export const FETCH_PATCHING_DETAILS_SUCCESS = 'FETCH_PATCHING_DETAILS_SUCCESS';
export const FETCH_PATCHING_DETAILS_FAILURE = 'FETCH_PATCHING_DETAILS_FAILURE';

export const FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_BEGIN =
  'FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_BEGIN';
export const FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_SUCCESS =
  'FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_SUCCESS';
export const FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_FAILURE =
  'FETCH_ALL_WORKSPACES_PATCHING_SUMMARY_FAILURE';
