export const FETCH_CATALOG_API_VERSION_BEGIN =
  'FETCH_CATALOG_API_VERSION_BEGIN';
export const FETCH_CATALOG_API_VERSION_SUCCESS =
  'FETCH_CATALOG_API_VERSION_SUCCESS';
export const FETCH_CATALOG_API_VERSION_FAILURE =
  'FETCH_CATALOG_API_VERSION_FAILURE';

export const FETCH_AZURE_STATUS_BEGIN = 'FETCH_AZURE_STATUS_BEGIN';
export const FETCH_AZURE_STATUS_SUCCESS = 'FETCH_AZURE_STATUS_SUCCESS';
export const FETCH_AZURE_STATUS_FAILURE = 'FETCH_AZURE_STATUS_FAILURE';

export const FETCH_CATALOG_TEMPLATES_BEGIN = 'FETCH_CATALOG_TEMPLATES_BEGIN';
export const FETCH_CATALOG_TEMPLATES_SUCCESS =
  'FETCH_CATALOG_TEMPLATES_SUCCESS';
export const FETCH_CATALOG_TEMPLATES_FAILURE =
  'FETCH_CATALOG_TEMPLATES_FAILURE';

export const FETCH_CATALOG_MACHINES_BEGIN = 'FETCH_CATALOG_MACHINES_BEGIN';
export const FETCH_CATALOG_MACHINES_SUCCESS = 'FETCH_CATALOG_MACHINES_SUCCESS';
export const FETCH_CATALOG_MACHINES_FAILURE = 'FETCH_CATALOG_MACHINES_FAILURE';

export const FETCH_CATALOG_MACHINE_SKUS_BEGIN =
  'FETCH_CATALOG_MACHINE_SKUS_BEGIN';
export const FETCH_CATALOG_MACHINE_SKUS_SUCCESS =
  'FETCH_CATALOG_MACHINE_SKUS_SUCCESS';
export const FETCH_CATALOG_MACHINE_SKUS_FAILURE =
  'FETCH_CATALOG_MACHINE_SKUS_FAILURE';

export const FETCH_CATALOG_USER_PROFILE_BEGIN =
  'FETCH_CATALOG_USER_PROFILE_BEGIN';
export const FETCH_CATALOG_USER_PROFILE_SUCCESS =
  'FETCH_CATALOG_USER_PROFILE_SUCCESS';
export const FETCH_CATALOG_USER_PROFILE_FAILURE =
  'FETCH_CATALOG_USER_PROFILE_FAILURE';

export const UPDATE_CATALOG_USER_PROFILE_BEGIN =
  'UPDATE_CATALOG_USER_PROFILE_BEGIN';
export const UPDATE_CATALOG_USER_PROFILE_SUCCESS =
  'UPDATE_CATALOG_USER_PROFILE_SUCCESS';
export const UPDATE_CATALOG_USER_PROFILE_FAILURE =
  'UPDATE_CATALOG_USER_PROFILE_FAILURE';

export const FETCH_USER_IMAGE_BEGIN = 'FETCH_USER_IMAGE_BEGIN';
export const FETCH_USER_IMAGE_SUCCESS = 'FETCH_USER_IMAGE_SUCCESS';
export const FETCH_USER_IMAGE_FAILURE = 'FETCH_USER_IMAGE_FAILURE';

export const FETCH_CATALOG_AGREEMENTS_BEGIN = 'FETCH_CATALOG_AGREEMENTS_BEGIN';
export const FETCH_CATALOG_AGREEMENTS_SUCCESS =
  'FETCH_CATALOG_AGREEMENTS_SUCCESS';
export const FETCH_CATALOG_AGREEMENTS_FAILURE =
  'FETCH_CATALOG_AGREEMENTS_FAILURE';

export const FETCH_CATALOG_REGIONS_BEGIN = 'FETCH_CATALOG_REGIONS_BEGIN';
export const FETCH_CATALOG_REGIONS_SUCCESS = 'FETCH_CATALOG_REGIONS_SUCCESS';
export const FETCH_CATALOG_REGIONS_FAILURE = 'FETCH_CATALOG_REGIONS_FAILURE';

export const FETCH_CATALOG_GEOGRAPHIES_BEGIN =
  'FETCH_CATALOG_GEOGRAPHIES_BEGIN';
export const FETCH_CATALOG_GEOGRAPHIES_SUCCESS =
  'FETCH_CATALOG_GEOGRAPHIES_SUCCESS';
export const FETCH_CATALOG_GEOGRAPHIES_FAILURE =
  'FETCH_CATALOG_GEOGRAPHIES_FAILURE';

export const FETCH_IS_ADMIN_BEGIN = 'FETCH_IS_ADMIN_BEGIN';
export const FETCH_IS_ADMIN_SUCCESS = 'FETCH_IS_ADMIN_SUCCESS';
export const FETCH_IS_ADMIN_FAILURE = 'FETCH_IS_ADMIN_FAILURE';

export const SET_USER_UNAUTHORIZED = 'SET_USER_UNAUTHORIZED';
export const SET_USER_AUTHORIZED = 'SET_USER_AUTHORIZED';

export const SET_JIT_ENABLED = 'SET_JIT_ENABLED';
export const SET_JIT_DISABLED = 'SET_JIT_DISABLED';

export const FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_BEGIN =
  'FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_BEGIN';
export const FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_SUCCESS =
  'FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_SUCCESS';
export const FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_FAILURE =
  'FETCH_AZURE_SUBSCRIPTION_QUOTA_STATUS_FAILURE';
export const SET_SELECTED_QUOTA_SUBSCRIPTION =
  'SET_SELECTED_QUOTA_SUBSCRIPTION';
export const SET_SELECTED_QUOTA_WORKSPACE_TENANT =
  'SET_SELECTED_QUOTA_WORKSPACE_TENANT';
export const SET_SELECTED_QUOTA_GEOGRAPHY = 'SET_SELECTED_QUOTA_GEOGRAPHY';

export const FETCH_TOURS_BEGIN = 'FETCH_TOURS_BEGIN';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILURE = 'FETCH_TOURS_FAILURE';
export const FETCH_HYPERLINKS_BEGIN = 'FETCH_HYPERLINKS_BEGIN';
export const FETCH_HYPERLINKS_SUCCESS = 'FETCH_HYPERLINKS_SUCCESS';
export const FETCH_HYPERLINKS_FAILURE = 'FETCH_HYPERLINKS_FAILURE';
export const FETCH_CATALOG_FEATURE_BEGIN = 'FETCH_CATALOG_FEATURE_BEGIN';
export const FETCH_CATALOG_FEATURE_SUCCESS = 'FETCH_CATALOG_FEATURE_SUCCESS';
export const FETCH_CATALOG_FEATURE_FAILURE = 'FETCH_CATALOG_FEATURE_FAILURE';
export const FETCH_CAMPAIGN_DEFINITIONS_BEGIN =
  'FETCH_CAMPAIGN_DEFINITIONS_BEGIN';
export const FETCH_CAMPAIGN_DEFINITIONS_SUCCESS =
  'FETCH_CAMPAIGN_DEFINITIONS_SUCCESS';
export const FETCH_CAMPAIGN_DEFINITIONS_FAILURE =
  'FETCH_CAMPAIGN_DEFINITIONS_FAILURE';
