export const FETCH_CONFIG_BEGIN = 'FETCH_CONFIG_BEGIN';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export const FETCH_FRONTEND_API_VERSION_BEGIN =
  'FETCH_FRONTEND_API_VERSION_BEGIN';
export const FETCH_FRONTEND_API_VERSION_SUCCESS =
  'FETCH_FRONTEND_API_VERSION_SUCCESS';
export const FETCH_FRONTEND_API_VERSION_FAILURE =
  'FETCH_FRONTEND_API_VERSION_FAILURE';

export const FETCH_APP_CONFIG_VALUES_BEGIN = 'FETCH_APP_CONFIG_VALUES_BEGIN';
export const FETCH_APP_CONFIG_VALUES_SUCCESS =
  'FETCH_APP_CONFIG_VALUES_SUCCESS';
export const FETCH_APP_CONFIG_VALUES_FAILURE =
  'FETCH_APP_CONFIG_VALUES_FAILURE';

export const FETCH_FEATURE_FLAGS_BEGIN = 'FETCH_FEATURE_FLAGS_BEGIN';
export const FETCH_FEATURE_FLAGS_SUCCESS = 'FETCH_FEATURE_FLAGS_SUCCESS';
export const FETCH_FEATURE_FLAGS_FAILURE = 'FETCH_FEATURE_FLAGS_FAILURE';
