export const EDITABLE_WORKSPACE_ADD_MACHINE = 'EDITABLE_WORKSPACE_ADD_MACHINE';
export const EDITABLE_WORKSPACE_REMOVE_MACHINE =
  'EDITABLE_WORKSPACE_REMOVE_MACHINE';
export const EDITABLE_WORKSPACE_UPDATE_NAME = 'EDITABLE_WORKSPACE_UPDATE_NAME';
export const EDITABLE_WORKSPACE_UPDATE_DOMAIN =
  'EDITABLE_WORKSPACE_UPDATE_DOMAIN';
export const EDITABLE_WORKSPACE_UPDATE_DESCRIPTION =
  'EDITABLE_WORKSPACE_UPDATE_DESCRIPTION';
export const EDIT_WORKSPACE_UPDATE_DESCRIPTION =
  'EDIT_WORKSPACE_UPDATE_DESCRIPTION';
export const EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_NAME =
  'EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_NAME';
export const EDITABLE_WORKSPACE_UPDATE_VM_NAME =
  'EDITABLE_WORKSPACE_UPDATE_VM_NAME';
export const EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_PASSWORD =
  'EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_PASSWORD';
export const EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_PASSWORD_CONFIRM =
  'EDITABLE_WORKSPACE_UPDATE_ADMINISTRATOR_PASSWORD_CONFIRM';
export const EDITABLE_WORKSPACE_UPDATE_MACHINE_MEMORY_GB =
  'EDITABLE_WORKSPACE_UPDATE_MACHINE_MEMORY_GB';
export const EDITABLE_WORKSPACE_UPDATE_MACHINE_OSDISK_GB =
  'EDITABLE_WORKSPACE_UPDATE_MACHINE_OSDISK_GB';
export const EDITABLE_WORKSPACE_UPDATE_WORKSPACE_EDIT_TYPE =
  'EDITABLE_WORKSPACE_UPDATE_WORKSPACE_EDIT_TYPE';
export const EDITABLE_WORKSPACE_ADD_DATA_DISK =
  'EDITABLE_WORKSPACE_ADD_DATA_DISK';
export const EDITABLE_WORKSPACE_REMOVE_DATA_DISK =
  'EDITABLE_WORKSPACE_REMOVE_DATA_DISK';
export const EDITABLE_WORKSPACE_BUILD_MACHINES =
  'EDITABLE_WORKSPACE_BUILD_MACHINES';
export const EDITABLE_WORKSPACE_UPDATE_DATA_DISK =
  'EDITABLE_WORKSPACE_UPDATE_DATA_DISK';
export const EDITABLE_WORKSPACE_UPDATE_GEOGRAPHY =
  'EDITABLE_WORKSPACE_UPDATE_GEOGRAPHY';
export const EDITABLE_WORKSPACE_UPDATE_OWNER =
  'EDITABLE_WORKSPACE_UPDATE_OWNER';
export const EDITABLE_WORKSPACE_UPDATE_WITH_TEMPLATE =
  'EDITABLE_WORKSPACE_UPDATE_WITH_TEMPLATE';
export const EDITABLE_WORKSPACE_RESET_TO_DEFAULT =
  'EDITABLE_WORKSPACE_RESET_TO_DEFAULT';
export const EDITABLE_WORKSPACE_RESET_CHANGES =
  'EDITABLE_WORKSPACE_RESET_CHANGES';
export const EDITABLE_WORKSPACE_RESET_WORKSPACE_CHANGES =
  'EDITABLE_WORKSPACE_RESET_WORKSPACE_CHANGES';
export const EDITABLE_WORKSPACE_RESET_SUBNET_CHANGES =
  'EDITABLE_WORKSPACE_RESET_SUBNET_CHANGES';
export const EDITABLE_WORKSPACE_UPDATE_DELETE_LOCK =
  'EDITABLE_WORKSPACE_UPDATE_DELETE_LOCK';
export const EDITABLE_WORKSPACE_ADD_SHARED_OWNER =
  'EDITABLE_WORKSPACE_ADD_SHARED_OWNER';
export const EDIT_WORKSPACE_UPDATE_OWNER = 'EDIT_WORKSPACE_UPDATE_OWNER';
export const EDITABLE_WORKSPACE_REMOVE_SHARED_OWNER =
  'EDITABLE_WORKSPACE_REMOVE_SHARED_OWNER';
export const EDIT_WORKSPACE_UPDATE_DATA_DISK =
  'EDIT_WORKSPACE_UPDATE_DATA_DISK';
export const EDITABLE_WORKSPACE_SET_CURRENT_WORKSPACE_EDIT =
  'EDITABLE_WORKSPACE_SET_CURRENT_WORKSPACE_EDIT';
export const EDITABLE_WORKSPACE_SET_CURRENT_WORKSPACE_NEW =
  'EDITABLE_WORKSPACE_SET_CURRENT_WORKSPACE_NEW';
export const EDITABLE_WORKSPACE_UPDATE_CURRENT_WORKSPACE_EDIT =
  'EDITABLE_WORKSPACE_UPDATE_CURRENT_WORKSPACE_EDIT';
export const EDITABLE_WORKSPACE_ADD_NEW_IP_ADDRESS =
  'EDITABLE_WORKSPACE_ADD_NEW_IP_ADDRESS';
export const EDITABLE_WORKSPACE_REMOVE_NEW_IP_ADDRESS =
  'EDITABLE_WORKSPACE_REMOVE_NEW_IP_ADDRESS';
export const EDITABLE_WORKSPACE_REMOVE_ALL_NEW_IP_ADDRESSES =
  'EDITABLE_WORKSPACE_REMOVE_ALL_NEW_IP_ADDRESSES';
export const EDITABLE_WORKSPACE_REMOVE_NAT_RULE =
  'EDITABLE_WORKSPACE_REMOVE_NAT_RULE';
export const EDITABLE_WORKSPACE_ADD_NAT_RULE =
  'EDITABLE_WORKSPACE_ADD_NAT_RULE';
export const EDITABLE_WORKSPACE_UPDATE_DNS_ZONE =
  'EDITABLE_WORKSPACE_UPDATE_DNS_ZONE';
export const EDITABLE_WORKSPACE_UPDATE_SUBNETS =
  'EDITABLE_WORKSPACE_UPDATE_SUBNETS';
export const EDITABLE_WORKSPACE_SET_SAVING = 'EDITABLE_WORKSPACE_SET_SAVING';
export const EDITABLE_WORKSPACE_ADD_NIC = 'EDITABLE_WORKSPACE_ADD_NIC';
export const EDITABLE_WORKSPACE_REMOVE_NIC = 'EDITABLE_WORKSPACE_REMOVE_NIC';
export const EDITABLE_WORKSPACE_CHANGE_PRIMARY_NIC =
  'EDITABLE_WORKSPACE_CHANGE_PRIMARY_NIC';
export const EDITABLE_WORKSPACE_CHANGE_NIC_SUBNET =
  'EDITABLE_WORKSPACE_CHANGE_NIC_SUBNET';
export const EDITABLE_WORKSPACE_REMOVE_CONFIGURED_MACHINE =
  'EDITABLE_WORKSPACE_REMOVE_CONFIGURED_MACHINE';
export const EDITABLE_WORKSPACE_RESET_MACHINE_SELECTION =
  'EDITABLE_WORKSPACE_RESET_MACHINE_SELECTION';
export const EDITABLE_WORKSPACE_SAVE_SUCCESS =
  'EDITABLE_WORKSPACE_SAVE_SUCCESS';
export const EDITABLE_WORKSPACE_SAVE_FAILURE =
  'EDITABLE_WORKSPACE_SAVE_FAILURE';
export const EDITABLE_WORKSPACE_UPDATE_WORKSPACE_SCHEDULED_JOB =
  'EDITABLE_WORKSPACE_UPDATE_WORKSPACE_SCHEDULED_JOB';
export const EDITABLE_WORKSPACE_SET_WORKSPACE_SCHEDULED_JOB =
  'EDITABLE_WORKSPACE_SET_WORKSPACE_SCHEDULED_JOB';
export const EDITABLE_WORKSPACE_SAVE_DNS_ZONE =
  'EDITABLE_WORKSPACE_SAVE_DNS_ZONE';
export const CREATE_SNAPSHOT_BEGIN = 'CREATE_SNAPSHOT_BEGIN';
export const CREATE_SNAPSHOT_SUCCESS = 'CREATE_SNAPSHOT_SUCCESS';
export const CREATE_SNAPSHOT_FAILURE = 'CREATE_SNAPSHOT_FAILURE';
export const RESTORE_SNAPSHOT_BEGIN = 'RESTORE_SNAPSHOT_BEGIN';
export const RESTORE_SNAPSHOT_SUCCESS = 'RESTORE_SNAPSHOT_SUCCESS';
export const RESTORE_SNAPSHOT_FAILURE = 'RESTORE_SNAPSHOT_FAILURE';
export const DELETE_SNAPSHOT_BEGIN = 'DELETE_SNAPSHOT_BEGIN';
export const DELETE_SNAPSHOT_SUCCESS = 'DELETE_SNAPSHOT_SUCCESS';
export const DELETE_SNAPSHOT_FAILURE = 'DELETE_SNAPSHOT_FAILURE';
export const EDITABLE_WORKSPACE_SET_NESTED_VIRTUALIZATION =
  'EDITABLE_WORKSPACE_SET_NESTED_VIRTUALIZATION';
export const EDITABLE_WORKSPACE_RESET_CONFIGURED_MACHINE_SELECTION =
  'EDITABLE_WORKSPACE_RESET_CONFIGURED_MACHINE_SELECTION';
export const REQUEST_RDP_BEGIN = 'REQUEST_RDP_BEGIN';
export const REQUEST_RDP_SUCCESS = 'REQUEST_RDP_SUCCESS';
export const REQUEST_RDP_FAILURE = 'REQUEST_RDP_FAILURE';
export const REVOKE_RDP_BEGIN = 'REVOKE_RDP_BEGIN';
export const REVOKE_RDP_SUCCESS = 'REVOKE_RDP_SUCCESS';
export const REVOKE_RDP_FAILURE = 'REVOKE_RDP_FAILURE';
export const EDITABLE_WORKSPACE_UPDATE_SEGMENT_SHARING =
  'EDITABLE_WORKSPACE_UPDATE_SEGMENT_SHARING';
