export const FETCH_FIREWALL_API_VERSION_BEGIN =
  'FETCH_FIREWALL_API_VERSION_BEGIN';
export const FETCH_FIREWALL_API_VERSION_SUCCESS =
  'FETCH_FIREWALL_API_VERSION_SUCCESS';
export const FETCH_FIREWALL_API_VERSION_FAILURE =
  'FETCH_FIREWALL_API_VERSION_FAILURE';

export const FETCH_JIT_ADDRESSES_BEGIN = 'FETCH_JIT_ADDRESSES_BEGIN';
export const FETCH_JIT_ADDRESSES_SUCCESS = 'FETCH_JIT_ADDRESSES_SUCCESS';
export const FETCH_JIT_ADDRESSES_FAILURE = 'FETCH_JIT_ADDRESSES_FAILURE';

export const ADD_JIT_ADDRESS_BEGIN = 'ADD_JIT_ADDRESS_BEGIN';
export const ADD_JIT_ADDRESS_SUCCESS = 'ADD_JIT_ADDRESS_SUCCESS';
export const ADD_JIT_ADDRESS_FAILURE = 'ADD_JIT_ADDRESS_FAILURE';

export const REMOVE_JIT_ADDRESS_BEGIN = 'REMOVE_JIT_ADDRESS_BEGIN';
export const REMOVE_JIT_ADDRESS_SUCCESS = 'REMOVE_JIT_ADDRESS_SUCCESS';
export const REMOVE_JIT_ADDRESS_FAILURE = 'REMOVE_JIT_ADDRESS_FAILURE';

export const FETCH_EC_JIT_ENTRIES_BEGIN = 'FETCH_EC_JIT_ENTRIES_BEGIN';
export const FETCH_EC_JIT_ENTRIES_SUCCESS = 'FETCH_EC_JIT_ENTRIES_SUCCESS';
export const FETCH_EC_JIT_ENTRIES_FAILURE = 'FETCH_EC_JIT_ENTRIES_FAILURE';

export const ACTIVATE_EC_JIT_ENTRY_BEGIN = 'ACTIVATE_EC_JIT_ENTRY_BEGIN';
export const ACTIVATE_EC_JIT_ENTRY_SUCCESS = 'ACTIVATE_EC_JIT_ENTRY_SUCCESS';
export const ACTIVATE_EC_JIT_ENTRY_FAILURE = 'ACTIVATE_EC_JIT_ENTRY_FAILURE';

export const DEACTIVATE_EC_JIT_ENTRY_BEGIN = 'DEACTIVATE_EC_JIT_ENTRY_BEGIN';
export const DEACTIVATE_EC_JIT_ENTRY_SUCCESS =
  'DEACTIVATE_EC_JIT_ENTRY_SUCCESS';
export const DEACTIVATE_EC_JIT_ENTRY_FAILURE =
  'DEACTIVATE_EC_JIT_ENTRY_FAILURE';

export const FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_BEGIN =
  'FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_BEGIN';
export const FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_SUCCESS =
  'FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_SUCCESS';
export const FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_FAILURE =
  'FETCH_JIT_ADDRESSES_FOR_ADMIN_WORKSPACE_FAILURE';
