export const SHOW_DEFAULT_NOTIFICATION = 'SHOW_DEFAULT_NOTIFICATION';
export const HIDE_DEFAULT_NOTIFICATION = 'HIDE_DEFAULT_NOTIFICATION';

export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION';
export const HIDE_ERROR_NOTIFICATION = 'HIDE_ERROR_NOTIFICATION';

export const SHOW_BLOCKED_NOTIFICATION = 'SHOW_BLOCKED_NOTIFICATION';
export const HIDE_BLOCKED_NOTIFICATION = 'HIDE_BLOCKED_NOTIFICATION';

export const SHOW_SEVERE_WARNING_NOTIFICATION =
  'SHOW_SEVERE_WARNING_NOTIFICATION';
export const HIDE_SEVERE_WARNING_NOTIFICATION =
  'HIDE_SEVERE_WARNING_NOTIFICATION';

export const SHOW_SUCCESS_NOTIFICATION = 'SHOW_SUCCESS_NOTIFICATION';
export const HIDE_SUCCESS_NOTIFICATION = 'HIDE_SUCCESS_NOTIFICATION';

export const SHOW_WARNING_NOTIFICATION = 'SHOW_WARNING_NOTIFICATION';
export const HIDE_WARNING_NOTIFICATION = 'HIDE_WARNING_NOTIFICATION';

export const SET_OPENED_PANEL_NAME = 'SET_OPENED_PANEL_NAME';
export const SHOW_USER_CONFIRMATION_DIALOG = 'SHOW_USER_CONFIRMATION_DIALOG';
export const HIDE_USER_CONFIRMATION_DIALOG = 'HIDE_USER_CONFIRMATION_DIALOG';

export const DISMISS_NOTIFICATIONS = 'DISMISS_NOTIFICATIONS';

export const FETCH_USER_NOTIFICATIONS_BEGIN = 'FETCH_USER_NOTIFICATIONS_BEGIN';
export const FETCH_USER_NOTIFICATIONS_SUCCESS =
  'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_FAILURE =
  'FETCH_USER_NOTIFICATIONS_FAILURE';

export const DISMISS_USER_NOTIFICATION_BEGIN =
  'DISMISS_USER_NOTIFICATION_BEGIN';
export const DISMISS_USER_NOTIFICATION_SUCCESS =
  'DISMISS_USER_NOTIFICATION_SUCCESS';
export const DISMISS_USER_NOTIFICATION_FAILURE =
  'DISMISS_USER_NOTIFICATION_FAILURE';

export const UPDATE_ALL_USER_NOTIFICATIONS_BEGIN =
  'UPDATE_ALL_USER_NOTIFICATIONS_BEGIN';
export const UPDATE_ALL_USER_NOTIFICATIONS_SUCCESS =
  'UPDATE_ALL_USER_NOTIFICATIONS_SUCCESS';
export const UPDATE_ALL_USER_NOTIFICATIONS_FAILURE =
  'UPDATE_ALL_USER_NOTIFICATIONS_FAILURE';

export const UPDATE_SUBSET_USER_NOTIFICATIONS_BEGIN =
  'UPDATE_SUBSET_USER_NOTIFICATIONS_BEGIN';
export const UPDATE_SUBSET_USER_NOTIFICATIONS_SUCCESS =
  'UPDATE_SUBSET_USER_NOTIFICATIONS_SUCCESS';
export const UPDATE_SUBSET_USER_NOTIFICATIONS_FAILURE =
  'UPDATE_SUBSET_USER_NOTIFICATIONS_FAILURE';

export const CHANGE_USER_NOTIFICATION_STATUS_BEGIN =
  'CHANGE_USER_NOTIFICATION_STATUS_BEGIN';
export const CHANGE_USER_NOTIFICATION_STATUS_SUCCESS =
  'CHANGE_USER_NOTIFICATION_STATUS_SUCCESS';
export const CHANGE_USER_NOTIFICATION_STATUS_FAILURE =
  'CHANGE_USER_NOTIFICATION_STATUS_FAILURE';

export const SET_USER_NOTIFICATION = 'SET_USER_NOTIFICATION';

export const SET_ASSERTIVE_SCREEN_READER_ANNOUNCEMENT =
  'SET_ASSERTIVE_SCREEN_READER_ANNOUNCEMENT';
export const SET_POLITE_SCREEN_READER_ANNOUNCEMENT =
  'SET_POLITE_SCREEN_READER_ANNOUNCEMENT';
