export const FETCH_WORKSPACE_SCHEDULED_JOBS_BEGIN =
  'FETCH_WORKSPACE_SCHEDULED_JOBS_BEGIN';
export const FETCH_WORKSPACE_SCHEDULED_JOBS_SUCCESS =
  'FETCH_WORKSPACE_SCHEDULED_JOBS_SUCCESS';
export const FETCH_WORKSPACE_SCHEDULED_JOBS_FAILURE =
  'FETCH_WORKSPACE_SCHEDULED_JOBS_FAILURE';
export const FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_BEGIN =
  'FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_BEGIN';
export const FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_SUCCESS =
  'FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_SUCCESS';
export const FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_FAILURE =
  'FETCH_ADMIN_WORKSPACE_SCHEDULED_JOB_FAILURE';
export const CREATE_WORKSPACE_SCHEDULED_JOB_BEGIN =
  'CREATE_WORKSPACE_SCHEDULED_JOB_BEGIN';
export const CREATE_WORKSPACE_SCHEDULED_JOB_SUCCESS =
  'CREATE_WORKSPACE_SCHEDULED_JOB_SUCCESS';
export const CREATE_WORKSPACE_SCHEDULED_JOB_FAILURE =
  'CREATE_WORKSPACE_SCHEDULED_JOB_FAILURE';
export const UPDATE_WORKSPACE_SCHEDULED_JOB_BEGIN =
  'UPDATE_WORKSPACE_SCHEDULED_JOB_BEGIN';
export const UPDATE_WORKSPACE_SCHEDULED_JOB_SUCCESS =
  'UPDATE_WORKSPACE_SCHEDULED_JOB_SUCCESS';
export const UPDATE_WORKSPACE_SCHEDULED_JOB_FAILURE =
  'UPDATE_WORKSPACE_SCHEDULED_JOB_FAILURE';
