parameters:
  - name: solution
    type: string
  - name: projectFolder
    type: string

jobs:
    - job:
      displayName: "NonProd CredScan - $(projectFolder)"
      pool:
        vmImage: "windows-latest"
      steps:
        - task: CredScan@2
          inputs:
            toolMajorVersion: "V2"
        - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
          displayName: "Component Detection"
          inputs:
            scanType: LogOnly
            failOnAlert: true
            sourceScanPath: "$(solution)/$(projectFolder)"
        - task: PostAnalysis@1
          inputs:
            AllTools: false
            APIScan: false
            BinSkim: false
            CodesignValidation: false
            CredScan: true
            FortifySCA: false
            FxCop: false
            ModernCop: false
            PoliCheck: false
            RoslynAnalyzers: false
            SDLNativeRules: false
            Semmle: false
            TSLint: false
            ToolLogsNotFoundAction: "Standard"
