parameters:
- name: 'env'
  type: string
- name: 'deploylocation'
  type: string
- name: 'devOpsEnv'
  type: string
- name: 'serviceConnection'
  type: string
- name: 'service'
  type: string
- name: 'label'
  type: string
- name: 'commonlabel'
  type: string
- name: 'appConfigEndpoint'
  type: string
- name: 'configFile'
  type: string
- name: 'kvrefFile'
  type: string
- name: 'commonkvrefFile'
  type: string
- name: 'appName'
  type: string
- name: 'packageName'

jobs:
  - job: 'DeployRelease'
  - deployment: 'Release_${{parameters.service}}_${{ parameters.env }}_${{ parameters.deploylocation}}'
    displayName: 'Release ${{parameters.service}} service to ${{ parameters.env }} for ${{ parameters.deploylocation}} region'
    environment: '${{ parameters.devOpsEnv }}'
    strategy:
      runOnce:
        deploy:
          steps:
           - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@3
             displayName: 'App Configuration - Upload config'
             inputs:
               azureSubscription: ${{parameters.serviceConnection}}
               AppConfigurationEndpoint: ${{parameters.appConfigEndpoint}}
               ConfigurationFile: ${{parameters.configFile}}
               Separator: .
               Label: ${{parameters.label}} 

           - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@3
             displayName: 'App Configuration - Upload kvref'
             inputs:
               azureSubscription: ${{parameters.serviceConnection}}
               AppConfigurationEndpoint: ${{parameters.appConfigEndpoint}}
               ConfigurationFile: ${{parameters.kvrefFile}}
               Separator: .
               Label: ${{parameters.label}} 
               ContentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
               
           - task: AzureAppConfiguration.azure-app-configuration-task-push.custom-build-release-task.AzureAppConfigurationPush@3
             displayName: 'App Configuration - Upload kvref'
             inputs:
               azureSubscription: ${{parameters.serviceConnection}}
               AppConfigurationEndpoint: ${{parameters.appConfigEndpoint}}
               ConfigurationFile: ${{parameters.commonkvrefFile}}
               Separator: .
               Label: ${{parameters.commonlabel}} 
               ContentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'

           - task: AzureFunctionApp@1
             displayName: 'Azure Function App Deploy: ${{parameters.appName}}'
             inputs:
               azureSubscription: ${{parameters.serviceConnection}}
               appType: functionApp
               appName: '${{parameters.appName}}'
               package: '${{parameters.packageName}}' 

