parameters:
- name: 'deploymentType'
  type: string
- name: 'env'
  type: string
- name: 'deploylocation'
  type: string
- name: 'devOpsEnv'
  type: string
- name: 'serviceConnection'
  type: string

jobs:
  - job: 'DeployResourceGroup'
  - deployment: 'DeployRG_${{ parameters.env }}_${{ parameters.deploylocation}}'
    displayName: 'Deploy RG to ${{ parameters.env }} for ${{ parameters.deploylocation}} region'
    environment: '${{ parameters.devOpsEnv }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Artifacts'
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureCLI@2
            displayName: 'Deploy resource group using Bicep with az cli for ${{ parameters.env }} into subscription: ${{ parameters.serviceConnection }} for ${{ parameters.deploylocation}} region'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment sub create --location ${{ parameters.deploylocation }} --template-file main-deploy-rg-${{ parameters.deploylocation }}.bicep --parameters parameters-rg-${{ parameters.env }}-${{ parameters.deploylocation }}.json'
              addSpnToEnvironment: true
              workingDirectory: '$(System.ArtifactsDirectory)/drop/Microsoft.MyWorkspace.Infrastructure/Bicep/${{ parameters.deploymentType }}'