parameters:
- name: 'deploymentType'
  type: string
- name: 'env'
  type: string
- name: 'deploylocation'
  type: string
- name: 'devOpsEnv'
  type: string
- name: 'serviceConnection'
  type: string
- name: 'resourceGroup'
  type: string


jobs:
  - job: 'DeployResources'
  - deployment: 'Deploy_Resources_${{ parameters.env }}_${{ parameters.deploylocation}}'
    displayName: 'Deploy MyWorkSpace Resources to ${{ parameters.env }} for ${{ parameters.deploylocation}} region'
    environment: '${{ parameters.devOpsEnv }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Artifacts'
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
    
          - task: AzureCLI@2
            displayName: 'Provision update resources using Bicep with az cli for ${{ parameters.env }} into RG ${{ parameters.resourceGroup }}'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --mode Incremental --resource-group ${{ parameters.resourceGroup }} -f main-deploy-resources.bicep --parameters parameters-resources-${{ parameters.env }}-${{ parameters.deploylocation}}.json'
              addSpnToEnvironment: true
              workingDirectory: '$(System.ArtifactsDirectory)/drop/Microsoft.MyWorkspace.Infrastructure/Bicep/${{ parameters.deploymentType }}'             