import { FirewallType } from 'src/types/AuthService/enums/FirewallType';
import { SegmentConstraintDto } from '../types/AuthService/SegmentConstraintDto.types';

export const DEFAULT_SEGMENT_CONSTRAINTS: SegmentConstraintDto = {
  MaxAzureWorkspacesAllowed: 0,
  MaxCumulativeMemoryAllowedCustom: 0,
  MaxCumulativeStorageAllowedCustom: 0,
  MaxMachineMemoryAllowedCustom: 0,
  MaxMachineStorageAllowedCustom: 0,
  MaxMachinesPerWorkspaceAllowedCustom: 0,
  MaxPublicIPAddressesAllowed: 0,
  MaxSnapshotsPerWorkspace: 1,
  MaxRunTimeAllowed: 0,
  MaxDataDisksPerVM: 0,
  FirewallType: FirewallType.PaloAlto,
  TopologyIds: [],
  ContentFilter: '',
  WeeklyRuntimeExtensionHours: 0,
  DisableAutoShutDown: true,
  MaxNestedWorkspacesAllowed: 0,
  MaxHypervHostMachinesAllowedPerWorkspace: 0,
  MaxMachineMemoryAllowedNested: 0,
  MaxMachineStorageAllowedNested: 0,
  EnableNestedDeployments: true,
  DisableCopyPaste: false,
  EnableAutoDeleteNonExistentUsers: false,
  EnableShareWithSegment: false,
  RestrictedDnsEndpoints: [],
  StaleWorkspaceDeletionDays: 10,
  EnableAutoStaleWorkspaceDeletion: true,
  MaxBulkDeleteWorkspacesThreshold: 100,
  MaxOSDiskSizeAllowed: 128,
  AllowTemplateCreation: false,
  EnablePatchInfoForVM: false,
  EnableWorkspaceScheduledStart: true,
  CancelScheduledStartAfterInactivityInDays: 0,
};
