# Copyright (c) Microsoft. All rights reserved.
trigger: none

pool:
  vmImage: 'windows-latest'
  
variables:
  - name: solution
    value: 'Microsoft.Vmas.Catalog'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'


name: PR_$(Date:yyMMdd)$(Rev:.r)

stages:
  - stage: NonProd_CheckCodeQuality
    jobs:
      - template: ../templates/codequality-stage.yml
        parameters:
          solution: '$(solution)'
          projectFolder: ['Microsoft.Vmas.Catalog.Api','Microsoft.Vmas.Catalog.DataTransferObjects','Microsoft.Vmas.Catalog.Models','Microsoft.Vmas.Catalog.Repository','Microsoft.Vmas.Catalog.Services']
          buildPlatform: '$(buildPlatform)'
          buildConfiguration: '$(buildConfiguration)'
